#ifndef __sp_gui_imp__
#define __sp_gui_imp__

/**
@file
Subclass of sp_gui, which is generated by wxFormBuilder.
*/

#include "sp_gui.h"
//// end generated include

#include <cstdlib>
#include <ctime>
#include "surface_projection.hpp"


/** Implementing sp_gui */
class sp_gui_imp : public sp_gui
{
protected:
  // Handlers for sp_gui events.
  void compute( wxCommandEvent& event );
  void close_app( wxCommandEvent& event );
  void repaint( wxCommandEvent& event );  
public:
  /** Constructor */
  sp_gui_imp( wxWindow* parent );
  //// end generated class members
  
private:
  
  void drawImg();
  wxBitmap *preview;
  wxImage *img;
};

#endif // __sp_gui_imp__
